/**
 * European country lists shared by registration and project forms.
 * Split into primary (DACH) and the rest so forms can render an optgroup separator.
 */
export const EU_PRIMARY_COUNTRIES = ['Deutschland', 'Österreich', 'Schweiz'] as const;

export const EU_OTHER_COUNTRIES = [
  'Albanien',
  'Andorra',
  'Belgien',
  'Bosnien und Herzegowina',
  'Bulgarien',
  'Dänemark',
  'Estland',
  'Finnland',
  'Frankreich',
  'Griechenland',
  'Irland',
  'Island',
  'Italien',
  'Kosovo',
  'Kroatien',
  'Lettland',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Malta',
  'Moldawien',
  'Monaco',
  'Montenegro',
  'Niederlande',
  'Nordmazedonien',
  'Norwegen',
  'Polen',
  'Portugal',
  'Rumänien',
  'San Marino',
  'Schweden',
  'Serbien',
  'Slowakei',
  'Slowenien',
  'Spanien',
  'Tschechien',
  'Ukraine',
  'Ungarn',
  'Vatikanstadt',
  'Vereinigtes Königreich',
  'Weißrussland',
  'Zypern',
] as const;
